# manual (marker for update script)
language: python
python:
    - 2.7
    - pypy-5.4.1
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
    - coverage run `which zope-testrunner` --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
