# manual (marker for update script)
language: python
sudo: false
python:
    - 2.7
    - pypy-5.4.1
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src --all
after_success:
    - coveralls
notifications:
    email: false
cache: pip
